/**
 * KnOT — Tailwind config
 * Mirrors the "Obsidian Nexus" design system (see the design folder's DESIGN.md).
 * Every color/font/spacing token below comes straight from that spec so the
 * React components can use the exact same class names as the design HTML.
 */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#ddb7ff",
        "on-primary": "#490080",
        "primary-container": "#b76dff",
        "on-primary-container": "#400071",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#2c0051",
        "on-primary-fixed-variant": "#6900b3",
        "inverse-primary": "#842bd2",
        secondary: "#4cd7f6",
        "on-secondary": "#003640",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: "#4edea3",
        "on-tertiary": "#003824",
        "tertiary-container": "#00a572",
        "on-tertiary-container": "#00311f",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "surface-tint": "#ddb7ff",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#cfc2d6",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        outline: "#988d9f",
        "outline-variant": "#4d4354",
        background: "#131313",
        "on-background": "#e2e2e2",
        // brand action colors used in the design's hover states
        "zap-yellow": "#facc15",
        "repost-green": "#22c55e",
        "like-red": "#ef4444",
        "thread-cyan": "#06b6d4",
        "hairline": "#2f3336",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-left": "275px",
        "sidebar-right": "350px",
        "feed-center": "600px",
        "container-max-width": "1265px",
        gutter: "12px",
        unit: "4px",
        "edge-margin": "16px",
      },
      maxWidth: {
        "container-max-width": "1265px",
        "feed-center": "600px",
      },
      fontFamily: {
        "mono-label": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
      },
      fontSize: {
        "mono-label": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        h2: ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        h1: ["23px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
